### ISSUE TITLE
The Official Docker Image Does Not Perform Graceful Shutdown

### ISSUE THREAD

**Issue by metapox** [postgresml/pgcat#773]
pgcat triggers a graceful shutdown with a SIGINT signal. It seems that the Dockerfile has been modified to set the STOPSIGNAL to SIGINT (see [Dockerfile](https://github.com/postgresml/pgcat/blob/main/Dockerfile#L22)).

However, when shutting down the official image (ghcr.io/postgresml/pgcat:latest), a SIGTERM is actually sent, causing all requests to terminate immediately.

We suspect that a different Dockerfile may be used when building the official image rather than the one provided.

While this issue can be avoided by creating and overriding with your own Dockerfile, it is a critical and potentially overlooked problem for many developers.

**Comment by drdrsh** [comment]
Hello, This is likely because the change in signal was introduced 2 month ago in this commit
https://github.com/postgresml/pgcat/commit/c34b15bddcb7cdff375f60e0b1ba64c2426909f0

Wheres the latest image published is from 7 months ago. I'll start working on a release to publish the latest image. 

Thank you for the report.

**Comment by drdrsh** [comment]
A new image was published which should have the the `STOPSIGNAL`  changes.
